name: nail_management
description: "A Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.2.0
  intl: ^0.20.2
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  path_provider: ^2.0.15
  image_picker: ^0.8.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
