// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8vBVJL3ExHA_8RvVU1J12TmqV7T_2ydo',
    appId: '1:145943091404:web:40c1d36caed573cbcd4a69',
    messagingSenderId: '145943091404',
    projectId: 'nail-management-5c918',
    authDomain: 'nail-management-5c918.firebaseapp.com',
    storageBucket: 'nail-management-5c918.firebasestorage.app',
    measurementId: 'G-1C58RTFSQF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDyvxNRR6JD7F7Q7lFcLpSBiHVyChYq4',
    appId: '1:145943091404:android:30309ff9fe87c85ecd4a69',
    messagingSenderId: '145943091404',
    projectId: 'nail-management-5c918',
    storageBucket: 'nail-management-5c918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO6dkLcEylbwGfDzIYzNpGSejoc1IrIIs',
    appId: '1:145943091404:ios:f9f79de9d880ea1fcd4a69',
    messagingSenderId: '145943091404',
    projectId: 'nail-management-5c918',
    storageBucket: 'nail-management-5c918.firebasestorage.app',
    iosBundleId: 'com.example.nailManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO6dkLcEylbwGfDzIYzNpGSejoc1IrIIs',
    appId: '1:145943091404:ios:a0d2cc24f330a886cd4a69',
    messagingSenderId: '145943091404',
    projectId: 'nail-management-5c918',
    storageBucket: 'nail-management-5c918.firebasestorage.app',
    iosBundleId: 'com.moonset.nailmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8vBVJL3ExHA_8RvVU1J12TmqV7T_2ydo',
    appId: '1:145943091404:web:b7f72a03b28efeb7cd4a69',
    messagingSenderId: '145943091404',
    projectId: 'nail-management-5c918',
    authDomain: 'nail-management-5c918.firebaseapp.com',
    storageBucket: 'nail-management-5c918.firebasestorage.app',
    measurementId: 'G-T768FYCRRN',
  );
}
