# Descomente ou adicione esta linha no topo do arquivo
platform :ios, '15.0'

# E adicione/modifique a seção post_install
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Força iOS 15 em todos os pods
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end